LSBPT: Edge Class Reference
Edge Class Reference
#include <edge.h>
Public Member Functions
Edge (Node *node1, Node *node2)
void setWeight (double w)
double getWeight ()
Node * getNode1 ()
Node * getNode2 ()
void setNode1 (Node *n)
void setNode2 (Node *n)
bool isForward () const
void setForward (bool value)
Node * traverse (Node *origin)
void replace (Node *old, Node *new_)
void setHeapIndex (unsigned long int i)
unsigned long int getHeapIndex ()
bool equals (Edge *other)
void setLength (unsigned int l)
unsigned int getLength ()
Edge * clone ()
Private Attributes
Node * node1
Node * node2
double weight
unsigned long int heapIndex
unsigned int length
bool forward
Detailed Description
Definition at line 30 of file edge.h.
Constructor & Destructor Documentation
Edge()
Edge::Edge (Node * node1, Node * node2)
Definition at line 22 of file edge.cpp.
References node1, and node2.
Referenced by clone().
Member Function Documentation
clone()
Edge * Edge::clone ()
Definition at line 107 of file edge.cpp.
References Edge(), getHeapIndex(), getLength(), getWeight(), node1, node2, setHeapIndex(), setLength(), and setWeight().
equals()
bool Edge::equals (Edge * other)
Definition at line 85 of file edge.cpp.
References getNode1(), getNode2(), node1, and node2.
getHeapIndex()
unsigned long Edge::getHeapIndex ()
Definition at line 81 of file edge.cpp.
References heapIndex.
Referenced by clone(), EdgeHeap::remove(), and EdgeHeap::update().
getLength()
unsigned int Edge::getLength ()
Definition at line 102 of file edge.cpp.
References length.
Referenced by clone(), and RAG::merge().
getNode1()
Node * Edge::getNode1 ()
Definition at line 38 of file edge.cpp.
References node1.
Referenced by EdgeHeap::edgeComparator(), equals(), RAG::merge(), and RAG::regionMerging().
getNode2()
Node * Edge::getNode2 ()
Definition at line 43 of file edge.cpp.
References node2.
Referenced by EdgeHeap::edgeComparator(), equals(), RAG::merge(), and RAG::regionMerging().
getWeight()
double Edge::getWeight ()
Definition at line 33 of file edge.cpp.
References weight.
Referenced by clone(), and EdgeHeap::edgeComparator().
isForward()
bool Edge::isForward () const
Definition at line 118 of file edge.cpp.
References forward.
replace()
void Edge::replace (Node * old, Node * new_)
Definition at line 67 of file edge.cpp.
References node1, and node2.
setForward()
void Edge::setForward (bool value)
Definition at line 123 of file edge.cpp.
References forward.
setHeapIndex()
void Edge::setHeapIndex (unsigned long int i)
Definition at line 77 of file edge.cpp.
References heapIndex.
Referenced by clone().
setLength()
void Edge::setLength (unsigned int l)
Definition at line 97 of file edge.cpp.
References length.
Referenced by initializer::addEdges(), clone(), initializer::connect(), and RAG::merge().
setNode1()
void Edge::setNode1 (Node * n)
Definition at line 48 of file edge.cpp.
References node1.
setNode2()
void Edge::setNode2 (Node * n)
Definition at line 53 of file edge.cpp.
References node2.
setWeight()
void Edge::setWeight (double w)
Definition at line 28 of file edge.cpp.
References weight.
Referenced by initializer::addEdges(), clone(), and initializer::connect().
traverse()
Node * Edge::traverse (Node * origin)
Definition at line 58 of file edge.cpp.
References node1, and node2.
Member Data Documentation
forward
bool Edge::forward private
Definition at line 84 of file edge.h.
Referenced by isForward(), and setForward().
heapIndex
unsigned long int Edge::heapIndex private
Definition at line 80 of file edge.h.
Referenced by getHeapIndex(), and setHeapIndex().
length
unsigned int Edge::length private
Definition at line 82 of file edge.h.
Referenced by getLength(), and setLength().
node1
Node* Edge::node1 private
Definition at line 75 of file edge.h.
Referenced by clone(), Edge(), equals(), getNode1(), replace(), setNode1(), and traverse().
node2
Node* Edge::node2 private
Definition at line 76 of file edge.h.
Referenced by clone(), Edge(), equals(), getNode2(), replace(), setNode2(), and traverse().
weight
double Edge::weight private
Definition at line 78 of file edge.h.
Referenced by getWeight(), and setWeight().
The documentation for this class was generated from the following files:
edge.h
edge.cpp