LSBPT: io Class Reference
io Class Reference
#include <io.h>
Public Member Functions
io ()
Static Public Member Functions
static void read2Mat (std::vector< Mat > *bands, GDALDataset *poDataset, size_t roiX, size_t roiY, size_t roiW, size_t roiH, bool ifDeleteNoise, std::vector< double > orderMin, std::vector< double > orderMax)
static void writeNodeToDisk (Node *node, int color[], GDALDataset *poDataset, int globalStartX, int globalStartY)
static void writeClassMap (Node *node, int classLabel, GDALDataset *poDataset, int globalStartX, int globalStartY)
static void writeNodeToCSV (Node *node, int label, ofstream &fout)
static void writeBoarderNodeToCSV (Node *node, int label, ofstream &fout, bool ifAddProbabilityModel)
static void writeBoarderNodeSetToCSV (std::vector< Node * > nodeSet, ofstream &fout, bool ifAddProbabilityModel)
static void createEmptyImage (std::string fileName, int width, int height, int nBandCount)
template<class T >
static void clip (T *buffer, const std::vector< double > &min, const std::vector< double > &max, int numBand, size_t numPixel)
template<class T >
static void rescale (T &thevalue, T min, T max, T rescaleMin, T rescaleMax)
static void bestSegmentation (Node *n, std::vector< Node * > &selectedNodes, double &cost, double lamda, bool useStdCut)
Detailed Description
Definition at line 34 of file io.h.
Constructor & Destructor Documentation
io::io ()
Definition at line 21 of file io.cpp.
Member Function Documentation
void io::bestSegmentation (Node * n, std::vector< Node * > & selectedNodes, double & cost, double lamda, bool useStdCut) static
Find a segmentation which minimized the energy function.
Parameters
n The root of the tree.
selectedNodes A vector of nodes where we store the segmentation
cost The total energy of the segmentation.
This method use dynamic programming to find the segmentation which minimize the energy function. It starts from the root, call itself recusively. When it visits a node, it call itselt to find the segmentation with minimum eneger of its left child node and right child node repectively. Then it compares the total enegy to maintain the segmentation of its two children and the energy to keep two children as one segment.
Definition at line 424 of file io.cpp.
References regionModel::cutCost(), Node::getLeftChild(), Node::getModel(), Node::getRightChild(), and Node::isLeaf().
Referenced by image::mergeBlockX(), image::mergeBlockY(), and imageblock::processing().
template<class T > static void io::clip (T * buffer, const std::vector< double > & min, const std::vector< double > & max, int numBand, size_t numPixel) inline static
Definition at line 67 of file io.h.
void io::createEmptyImage (std::string fileName, int width, int height, int nBandCount) static
Definition at line 208 of file io.cpp.
Referenced by paintHoover().
void io::read2Mat (std::vector< Mat > * bands, GDALDataset * poDataset, size_t roiX, size_t roiY, size_t roiW, size_t roiH, bool ifDeleteNoise, std::vector< double > orderMin, std::vector< double > orderMax) static
Read a part of the image
This method read the color information of a tile of a large image, and store it in *bands. The start point and size of the tile are indicated in parameters. It is possible to delete some outliers by setting all values which out of the range, indicated in parameters orderMin and orderMax
Parameters
*bands To store the color information, each Mat stores one band
*poDataset A GDALDataset object indicates where to read the data
rioX start point of horizontal direction of the current tile
roiY Start point of verticle direction of the current tile
roiW The size of the current tile in horizontal direction
roiH The size of the current tile in verticle direction
Definition at line 27 of file io.cpp.
Referenced by imageblock::loadBlock().
template<class T > static void io::rescale (T & thevalue, T min, T max, T rescaleMin, T rescaleMax) inline static
Definition at line 96 of file io.h.
void io::writeBoarderNodeSetToCSV (std::vector< Node * > nodeSet, ofstream & fout, bool ifAddProbabilityModel) static
Definition at line 407 of file io.cpp.
References writeBoarderNodeToCSV().
void io::writeBoarderNodeToCSV (Node * node, int label, ofstream & fout, bool ifAddProbabilityModel) static
Definition at line 346 of file io.cpp.
References Node::getBoarderIndexX(), Node::getBoarderIndexY(), Node::getLeftChild(), Node::getMeanSpectrum(), Node::getPosition(), Node::getProbability(), Node::getRightChild(), and Node::isLeaf().
Referenced by imageblock::saveToDisk(), image::saveToDisk(), and writeBoarderNodeSetToCSV().
void io::writeClassMap (Node * node, int classLabel, GDALDataset * poDataset, int globalStartX, int globalStartY) static
Definition at line 284 of file io.cpp.
References Node::getLeftChild(), Node::getPosition(), Node::getRightChild(), and Node::isLeaf().
Referenced by imageblock::saveToDisk(), and image::saveToDisk().
void io::writeNodeToCSV (Node * node, int label, ofstream & fout) static
Definition at line 315 of file io.cpp.
References Node::getLeftChild(), Node::getPosition(), Node::getRightChild(), and Node::isLeaf().
Referenced by imageblock::saveToDisk(), and image::saveToDisk().
void io::writeNodeToDisk (Node * node, int color[], GDALDataset * poDataset, int globalStartX, int globalStartY) static
Definition at line 259 of file io.cpp.
References Node::getLeftChild(), Node::getPosition(), Node::getRightChild(), and Node::isLeaf().
Referenced by imageblock::saveToDisk(), and image::saveToDisk().
The documentation for this class was generated from the following files:
io.h
io.cpp