LSBPT: regionModel Class Reference
regionModel Class Reference abstract
#include <regionModel.h>
Public Member Functions
virtual ~regionModel ()
virtual regionModel * merge (regionModel *other)=0
virtual regionModel * getModel ()=0
virtual double getOrder (regionModel *other)=0
virtual float getMeanSpectrumAt (unsigned short band)=0
virtual unsigned short getLowestCostClass ()=0
virtual regionModel * clone ()=0
virtual double cutCost (bool useStdCut)=0
virtual void setNode (Node *n)
Node * getNode ()
void setArea (unsigned long a)
unsigned long getArea ()
virtual void printHistogram ()=0
virtual std::vector< double > getProbability ()=0
virtual std::vector< float > getMeanSpectrum ()=0
Public Attributes
bool useStdCut
Protected Attributes
Node * node
unsigned long area
Detailed Description
Definition at line 29 of file regionModel.h.
Constructor & Destructor Documentation
~regionModel()
virtual regionModel::~regionModel () inline virtual
Definition at line 33 of file regionModel.h.
Member Function Documentation
clone()
virtual regionModel* regionModel::clone () pure virtual
Implemented in histogramModel, compoundModel, and probabilityModel.
cutCost()
virtual double regionModel::cutCost (bool useStdCut) pure virtual
Implemented in probabilityModel, histogramModel, and compoundModel.
Referenced by io::bestSegmentation().
getArea()
unsigned long regionModel::getArea ()
Definition at line 41 of file regionModel.cpp.
References area.
Referenced by Node::getArea(), compoundModel::getOrder(), probabilityModel::merge(), compoundModel::merge(), and histogramModel::merge().
getLowestCostClass()
virtual unsigned short regionModel::getLowestCostClass () pure virtual
Implemented in histogramModel, probabilityModel, and compoundModel.
getMeanSpectrum()
virtual std::vector<float> regionModel::getMeanSpectrum () pure virtual
Implemented in probabilityModel, histogramModel, and compoundModel.
Referenced by Node::getMeanSpectrum().
getMeanSpectrumAt()
virtual float regionModel::getMeanSpectrumAt (unsigned short band) pure virtual
Implemented in probabilityModel, histogramModel, and compoundModel.
Referenced by Node::getMeanSpectrumAt().
getModel()
virtual regionModel* regionModel::getModel () pure virtual
Implemented in probabilityModel, histogramModel, and compoundModel.
getNode()
Node * regionModel::getNode ()
Definition at line 31 of file regionModel.cpp.
References node.
getOrder()
virtual double regionModel::getOrder (regionModel * other) pure virtual
Implemented in compoundModel, histogramModel, and probabilityModel.
Referenced by initializer::addEdges(), and initializer::connect().
getProbability()
virtual std::vector<double> regionModel::getProbability () pure virtual
Implemented in histogramModel, probabilityModel, and compoundModel.
Referenced by Node::getClassLabel(), and Node::getProbability().
merge()
virtual regionModel* regionModel::merge (regionModel * other) pure virtual
Implemented in histogramModel, compoundModel, and probabilityModel.
Referenced by RAG::merge().
printHistogram()
virtual void regionModel::printHistogram () pure virtual
Implemented in histogramModel, probabilityModel, and compoundModel.
setArea()
void regionModel::setArea (unsigned long a)
Definition at line 36 of file regionModel.cpp.
References area.
Referenced by probabilityModel::clone(), compoundModel::clone(), histogramModel::clone(), histogramModel::histogramModel(), probabilityModel::merge(), compoundModel::merge(), histogramModel::merge(), and probabilityModel::probabilityModel().
setNode()
void regionModel::setNode (Node * n) virtual
Reimplemented in compoundModel.
Definition at line 26 of file regionModel.cpp.
References node.
Referenced by Node::setModel(), and compoundModel::setNode().
Member Data Documentation
area
unsigned long regionModel::area protected
Definition at line 66 of file regionModel.h.
Referenced by probabilityModel::clone(), compoundModel::clone(), histogramModel::clone(), compoundModel::compoundModel(), histogramModel::cutCost(), getArea(), and setArea().
node
Node* regionModel::node protected
Definition at line 65 of file regionModel.h.
Referenced by getNode(), compoundModel::setNode(), and setNode().
useStdCut
bool regionModel::useStdCut
Definition at line 61 of file regionModel.h.
The documentation for this class was generated from the following files:
regionModel.h
regionModel.cpp