LSBPT: EdgeHeap Class Reference
EdgeHeap Class Reference
#include <edgeheap.h>
Public Member Functions
EdgeHeap ()
~EdgeHeap ()
void push_back (Edge *e)
void heapify ()
void insert (Edge *e)
Edge * getFront ()
Edge * getHeap (int ind)
void removeFront ()
void remove (Edge *e)
void clearAll ()
long int size ()
void randomShuffle ()
Edge * getAt (long int pos)
void update (Edge *e)
bool isHeap ()
Static Public Member Functions
static bool edgeComparator (Edge *e1, Edge *e2)
Private Member Functions
unsigned long int heapifyUp (unsigned long pos)
void heapifyDown (long int pos)
void updateAt (long int pos)
void removeAt (long int pos)
Private Attributes
std::vector< Edge * > heap
Detailed Description
Definition at line 39 of file edgeheap.h.
Constructor & Destructor Documentation
EdgeHeap()
EdgeHeap::EdgeHeap ()
Definition at line 23 of file edgeheap.cpp.
~EdgeHeap()
EdgeHeap::~EdgeHeap ()
Definition at line 27 of file edgeheap.cpp.
Member Function Documentation
clearAll()
void EdgeHeap::clearAll ()
Definition at line 312 of file edgeheap.cpp.
References heap.
edgeComparator()
bool EdgeHeap::edgeComparator (Edge * e1, Edge * e2) static
Definition at line 51 of file edgeheap.cpp.
References Node::getArea(), Edge::getNode1(), Edge::getNode2(), Node::getPosition(), and Edge::getWeight().
Referenced by heapify(), heapifyDown(), heapifyUp(), isHeap(), removeAt(), and updateAt().
getAt()
Edge * EdgeHeap::getAt (long int pos)
Definition at line 330 of file edgeheap.cpp.
References heap.
getFront()
Edge * EdgeHeap::getFront ()
Definition at line 260 of file edgeheap.cpp.
References heap.
Referenced by RAG::regionMerging().
getHeap()
Edge * EdgeHeap::getHeap (int ind)
Definition at line 266 of file edgeheap.cpp.
References heap.
heapify()
void EdgeHeap::heapify ()
Definition at line 38 of file edgeheap.cpp.
References edgeComparator(), and heap.
Referenced by RAG::regionMerging().
heapifyDown()
void EdgeHeap::heapifyDown (long int pos) private
Definition at line 453 of file edgeheap.cpp.
References edgeComparator(), and heap.
Referenced by removeAt(), and updateAt().
heapifyUp()
unsigned long EdgeHeap::heapifyUp (unsigned long pos) private
Definition at line 418 of file edgeheap.cpp.
References edgeComparator(), and heap.
Referenced by insert(), removeAt(), and updateAt().
insert()
void EdgeHeap::insert (Edge * e)
Definition at line 250 of file edgeheap.cpp.
References heap, and heapifyUp().
isHeap()
bool EdgeHeap::isHeap ()
Definition at line 376 of file edgeheap.cpp.
References edgeComparator(), and heap.
push_back()
void EdgeHeap::push_back (Edge * e)
Definition at line 31 of file edgeheap.cpp.
References heap.
Referenced by RAG::addEdge().
randomShuffle()
void EdgeHeap::randomShuffle ()
Definition at line 324 of file edgeheap.cpp.
References heap.
remove()
void EdgeHeap::remove (Edge * e)
Definition at line 355 of file edgeheap.cpp.
References Edge::getHeapIndex(), and removeAt().
Referenced by RAG::merge().
removeAt()
void EdgeHeap::removeAt (long int pos) private
Definition at line 277 of file edgeheap.cpp.
References edgeComparator(), heap, heapifyDown(), and heapifyUp().
Referenced by remove(), and removeFront().
removeFront()
void EdgeHeap::removeFront ()
Definition at line 272 of file edgeheap.cpp.
References removeAt().
Referenced by RAG::regionMerging().
size()
long EdgeHeap::size ()
Definition at line 319 of file edgeheap.cpp.
References heap.
Referenced by RAG::getEdgeSize(), and RAG::regionMerging().
update()
void EdgeHeap::update (Edge * e)
Definition at line 366 of file edgeheap.cpp.
References Edge::getHeapIndex(), and updateAt().
Referenced by RAG::merge().
updateAt()
void EdgeHeap::updateAt (long int pos) private
Definition at line 335 of file edgeheap.cpp.
References edgeComparator(), heap, heapifyDown(), and heapifyUp().
Referenced by update().
Member Data Documentation
heap
std::vector<Edge*> EdgeHeap::heap private
Definition at line 90 of file edgeheap.h.
Referenced by clearAll(), getAt(), getFront(), getHeap(), heapify(), heapifyDown(), heapifyUp(), insert(), isHeap(), push_back(), randomShuffle(), removeAt(), size(), and updateAt().
The documentation for this class was generated from the following files:
edgeheap.h
edgeheap.cpp