LSBPT: compoundModel Class Reference
compoundModel Class Reference
#include <compoundmodel.h>
Public Member Functions
compoundModel ()
compoundModel (histogramModel *histogramModelTemp, probabilityModel *probabilityModelTemp)
compoundModel (histogramModel *histogramModelTemp)
virtual ~compoundModel ()
regionModel * merge (regionModel *other)
compoundModel * getModel ()
double getOrder (regionModel *other)
compoundModel * clone ()
double cutCost (bool useStdCut)
void setNode (Node *n)
void setHistogramModel (histogramModel *hist_model)
histogramModel * getHistogramModel ()
float getMeanSpectrumAt (unsigned short band)
unsigned short getLowestCostClass ()
void printHistogram ()
void setProbModel (probabilityModel *prob_model)
probabilityModel * getProbModel ()
std::vector< double > getProbability ()
std::vector< float > getMeanSpectrum ()
Public Member Functions inherited from regionModel
virtual ~regionModel ()
Node * getNode ()
void setArea (unsigned long a)
unsigned long getArea ()
Public Attributes
double alpha
double lambda
Public Attributes inherited from regionModel
bool useStdCut
Static Public Attributes
static double areaExponent
static bool areaWeighted
static long floor
static bool ifUseMinimumToMerge = false
static double probabilityModelWeight = 0
Private Attributes
histogramModel * hist_model
probabilityModel * prob_model
Additional Inherited Members
Protected Attributes inherited from regionModel
Node * node
unsigned long area
Detailed Description
Definition at line 29 of file compoundmodel.h.
Constructor & Destructor Documentation
compoundModel() [1/3]
compoundModel::compoundModel ()
Definition at line 31 of file compoundmodel.cpp.
References alpha, regionModel::area, hist_model, and prob_model.
Referenced by clone(), and merge().
compoundModel() [2/3]
compoundModel::compoundModel (histogramModel * histogramModelTemp, probabilityModel * probabilityModelTemp)
Definition at line 39 of file compoundmodel.cpp.
References alpha, regionModel::area, hist_model, and prob_model.
compoundModel() [3/3]
compoundModel::compoundModel (histogramModel * histogramModelTemp)
Definition at line 47 of file compoundmodel.cpp.
References alpha, regionModel::area, hist_model, and prob_model.
~compoundModel()
compoundModel::~compoundModel () virtual
Definition at line 57 of file compoundmodel.cpp.
References hist_model, and prob_model.
Member Function Documentation
clone()
compoundModel * compoundModel::clone () virtual
Implements regionModel.
Definition at line 264 of file compoundmodel.cpp.
References regionModel::area, histogramModel::clone(), compoundModel(), hist_model, regionModel::setArea(), and setHistogramModel().
cutCost()
double compoundModel::cutCost (bool useStdCut) virtual
Implements regionModel.
Definition at line 281 of file compoundmodel.cpp.
References histogramModel::cutCost(), probabilityModel::cutCost(), hist_model, and prob_model.
getHistogramModel()
histogramModel * compoundModel::getHistogramModel ()
Definition at line 312 of file compoundmodel.cpp.
References hist_model.
Referenced by getOrder(), and merge().
getLowestCostClass()
unsigned short compoundModel::getLowestCostClass () virtual
Implements regionModel.
Definition at line 323 of file compoundmodel.cpp.
References probabilityModel::getLowestCostClass(), and prob_model.
getMeanSpectrum()
std::vector< float > compoundModel::getMeanSpectrum () virtual
Implements regionModel.
Definition at line 104 of file compoundmodel.cpp.
References histogramModel::getMeanSpectrum(), and hist_model.
Referenced by printHistogram().
getMeanSpectrumAt()
float compoundModel::getMeanSpectrumAt (unsigned short band) virtual
Implements regionModel.
Definition at line 318 of file compoundmodel.cpp.
References histogramModel::getMeanSpectrumAt(), and hist_model.
getModel()
compoundModel * compoundModel::getModel () virtual
Implements regionModel.
Definition at line 92 of file compoundmodel.cpp.
getOrder()
double compoundModel::getOrder (regionModel * other) virtual
Implements regionModel.
Definition at line 163 of file compoundmodel.cpp.
References alpha, areaExponent, areaWeighted, floor, regionModel::getArea(), getHistogramModel(), probabilityModel::getOrder(), histogramModel::getOrder(), getProbModel(), ifUseMinimumToMerge, prob_model, and probabilityModelWeight.
getProbability()
std::vector< double > compoundModel::getProbability () virtual
Implements regionModel.
Definition at line 96 of file compoundmodel.cpp.
References probabilityModel::getProbability(), and prob_model.
Referenced by printHistogram().
getProbModel()
probabilityModel * compoundModel::getProbModel ()
Definition at line 333 of file compoundmodel.cpp.
References prob_model.
Referenced by getOrder(), merge(), and printHistogram().
merge()
regionModel * compoundModel::merge (regionModel * other) virtual
Implements regionModel.
Definition at line 67 of file compoundmodel.cpp.
References compoundModel(), regionModel::getArea(), getHistogramModel(), getProbModel(), hist_model, probabilityModel::merge(), histogramModel::merge(), prob_model, regionModel::setArea(), setHistogramModel(), and setProbModel().
printHistogram()
void compoundModel::printHistogram () inline virtual
Implements regionModel.
Definition at line 54 of file compoundmodel.h.
References getMeanSpectrum(), getProbability(), getProbModel(), histogramModel::printHistogram(), prob_model, and setProbModel().
setHistogramModel()
void compoundModel::setHistogramModel (histogramModel * hist_model)
Definition at line 306 of file compoundmodel.cpp.
References hist_model.
Referenced by initializer::addEmpytHistModel(), clone(), and merge().
setNode()
void compoundModel::setNode (Node * n) virtual
Reimplemented from regionModel.
Definition at line 295 of file compoundmodel.cpp.
References hist_model, regionModel::node, and regionModel::setNode().
setProbModel()
void compoundModel::setProbModel (probabilityModel * prob_model)
Definition at line 327 of file compoundmodel.cpp.
References prob_model.
Referenced by merge(), and printHistogram().
Member Data Documentation
alpha
double compoundModel::alpha
Definition at line 68 of file compoundmodel.h.
Referenced by compoundModel(), and getOrder().
areaExponent
double compoundModel::areaExponent static
Definition at line 72 of file compoundmodel.h.
Referenced by getOrder(), and image::setGlobalSettings().
areaWeighted
bool compoundModel::areaWeighted static
Definition at line 73 of file compoundmodel.h.
Referenced by getOrder(), and image::setGlobalSettings().
floor
long compoundModel::floor static
Definition at line 74 of file compoundmodel.h.
Referenced by getOrder(), and image::setGlobalSettings().
hist_model
histogramModel* compoundModel::hist_model private
Definition at line 81 of file compoundmodel.h.
Referenced by clone(), compoundModel(), cutCost(), getHistogramModel(), getMeanSpectrum(), getMeanSpectrumAt(), merge(), setHistogramModel(), setNode(), and ~compoundModel().
ifUseMinimumToMerge
bool compoundModel::ifUseMinimumToMerge = false static
Definition at line 75 of file compoundmodel.h.
Referenced by getOrder(), and image::setGlobalSettings().
lambda
double compoundModel::lambda
Definition at line 69 of file compoundmodel.h.
prob_model
probabilityModel* compoundModel::prob_model private
Definition at line 82 of file compoundmodel.h.
Referenced by compoundModel(), cutCost(), getLowestCostClass(), getOrder(), getProbability(), getProbModel(), merge(), printHistogram(), setProbModel(), and ~compoundModel().
probabilityModelWeight
double compoundModel::probabilityModelWeight = 0 static
Definition at line 76 of file compoundmodel.h.
Referenced by getOrder(), and image::setGlobalSettings().
The documentation for this class was generated from the following files:
compoundmodel.h
compoundmodel.cpp