LSBPT: hoovermetrics.cpp File Reference
hoovermetrics.cpp File Reference
#include "hoovermetrics.h"
Classes
struct FirstColumnOnlyCmp
Functions
static bool pixelComparator (std::vector< int > Pixel_1, std::vector< int > Pixel_2)
static bool vectorComparator (std::vector< int32_t > pixel_1, std::vector< int32_t > pixel_2)
void readLabelImage (std::string fileName, int &numRegions, std::vector< std::vector< int > > *image)
void LoadImage (std::string fileName, int &numRegions, std::vector< std::vector< int > > *image)
void computeTable (std::vector< std::vector< int > > &image_1, std::vector< std::vector< int > > &image_2, std::vector< std::vector< int > > *hooverTable, std::vector< int > *image_1_regions, std::vector< int > *image_2_regions)
void regionsClassification (std::vector< int > &image_1_regions, std::vector< int > &image_2_regions, std::vector< std::vector< int > > &hooverTable, std::vector< int > *regionType_1, std::vector< int > *regionType_2, float tolerance)
void computerHooverMetrics (std::vector< int > &image_1_regions, std::vector< int > &image_2_regions, std::vector< int > &regionType_1, std::vector< int > &regionType_2)
void paintHoover (std::vector< std::vector< int > > &image, std::vector< int > &regionType, std::string fileName_save)
void hooverCompare (std::string fileName1, std::string fileName2, std::string fileName_save, float tolerance)
Function Documentation
computerHooverMetrics()
void computerHooverMetrics (std::vector< int > & image_1_regions, std::vector< int > & image_2_regions, std::vector< int > & regionType_1, std::vector< int > & regionType_2)
Definition at line 334 of file hoovermetrics.cpp.
Referenced by hooverCompare().
computeTable()
void computeTable (std::vector< std::vector< int > > & image_1, std::vector< std::vector< int > > & image_2, std::vector< std::vector< int > > * hooverTable, std::vector< int > * image_1_regions, std::vector< int > * image_2_regions)
Definition at line 175 of file hoovermetrics.cpp.
Referenced by hooverCompare().
hooverCompare()
void hooverCompare (std::string fileName1, std::string fileName2, std::string fileName_save, float tolerance)
Definition at line 506 of file hoovermetrics.cpp.
References computerHooverMetrics(), computeTable(), LoadImage(), paintHoover(), pixelComparator(), readLabelImage(), and regionsClassification().
Referenced by HooverCalculator::on_ComputeHoover_clicked().
LoadImage()
void LoadImage (std::string fileName, int & numRegions, std::vector< std::vector< int > > * image)
Definition at line 138 of file hoovermetrics.cpp.
Referenced by hooverCompare().
paintHoover()
void paintHoover (std::vector< std::vector< int > > & image, std::vector< int > & regionType, std::string fileName_save)
Definition at line 437 of file hoovermetrics.cpp.
References io::createEmptyImage().
Referenced by hooverCompare().
pixelComparator()
static bool pixelComparator (std::vector< int > Pixel_1, std::vector< int > Pixel_2) static
Definition at line 17 of file hoovermetrics.cpp.
Referenced by hooverCompare().
readLabelImage()
void readLabelImage (std::string fileName, int & numRegions, std::vector< std::vector< int > > * image)
Definition at line 66 of file hoovermetrics.cpp.
References vectorComparator().
Referenced by hooverCompare().
regionsClassification()
void regionsClassification (std::vector< int > & image_1_regions, std::vector< int > & image_2_regions, std::vector< std::vector< int > > & hooverTable, std::vector< int > * regionType_1, std::vector< int > * regionType_2, float tolerance)
Definition at line 216 of file hoovermetrics.cpp.
Referenced by hooverCompare().
vectorComparator()
static bool vectorComparator (std::vector< int32_t > pixel_1, std::vector< int32_t > pixel_2) static
Definition at line 46 of file hoovermetrics.cpp.
Referenced by readLabelImage().