LSBPT: hoovermetrics.h File Reference
hoovermetrics.h File Reference
#include <vector>
#include <string>
#include <fstream>
#include <sstream>
#include <iostream>
#include <cstdlib>
#include "io.h"
Functions
void computeTable (std::vector< std::vector< int > > &image_1, std::vector< std::vector< int > > &image_2, std::vector< std::vector< int > > *hooverTable, std::vector< int > *image_1_regions, std::vector< int > *image_2_regions)
void regionsClassification (std::vector< int > &image_1_regions, std::vector< int > &image_2_regions, std::vector< std::vector< int > > &hooverTable, std::vector< int > *regionType_1, std::vector< int > *regionType_2, float tolerance)
void computerHooverMetrics (std::vector< int > &image_1_regions, std::vector< int > &image_2_regions, std::vector< int > &regionType_1, std::vector< int > &regionType_2)
void paintHoover (std::vector< std::vector< int > > &image, std::vector< int > &regionType, std::string fileName_save)
void hooverCompare (std::string fileName1, std::string fileName2, std::string fileName_save, float tolerance)
Function Documentation
computerHooverMetrics()
void computerHooverMetrics (std::vector< int > & image_1_regions, std::vector< int > & image_2_regions, std::vector< int > & regionType_1, std::vector< int > & regionType_2)
Definition at line 334 of file hoovermetrics.cpp.
Referenced by hooverCompare().
computeTable()
void computeTable (std::vector< std::vector< int > > & image_1, std::vector< std::vector< int > > & image_2, std::vector< std::vector< int > > * hooverTable, std::vector< int > * image_1_regions, std::vector< int > * image_2_regions)
Definition at line 175 of file hoovermetrics.cpp.
Referenced by hooverCompare().
hooverCompare()
void hooverCompare (std::string fileName1, std::string fileName2, std::string fileName_save, float tolerance)
Definition at line 506 of file hoovermetrics.cpp.
References computerHooverMetrics(), computeTable(), LoadImage(), paintHoover(), pixelComparator(), readLabelImage(), and regionsClassification().
Referenced by HooverCalculator::on_ComputeHoover_clicked().
paintHoover()
void paintHoover (std::vector< std::vector< int > > & image, std::vector< int > & regionType, std::string fileName_save)
Definition at line 437 of file hoovermetrics.cpp.
References io::createEmptyImage().
Referenced by hooverCompare().
regionsClassification()
void regionsClassification (std::vector< int > & image_1_regions, std::vector< int > & image_2_regions, std::vector< std::vector< int > > & hooverTable, std::vector< int > * regionType_1, std::vector< int > * regionType_2, float tolerance)
Definition at line 216 of file hoovermetrics.cpp.
Referenced by hooverCompare().