LSBPT: histogramModel Class Reference
histogramModel Class Reference
#include <histogrammodel.h>
Public Member Functions
histogramModel (unsigned short bands, unsigned short bins)
histogramModel (const std::vector< float > &spectrum, unsigned nBins, const std::vector< double > &min, const std::vector< double > &max)
virtual ~histogramModel ()
double getOrder (regionModel *other)
histogramModel * merge (regionModel *other)
histogramModel * getModel ()
void setHistogramValue (unsigned short band, unsigned short bin, float p)
void increaseHistogramValue (unsigned short band, unsigned short bin)
void increaseHistogramValueBy (unsigned short band, unsigned short bin, float v)
float getValue (unsigned short band, unsigned short bin)
const std::vector< float > & getBand (unsigned short b)
unsigned short getNBands ()
unsigned short getNBins ()
void normalizeBand (unsigned short band)
std::vector< float > & getSpectrum ()
std::vector< float > & getStd ()
void setMeanSpectrumAt (unsigned short band, float value)
void setStd (unsigned short band, float value)
float getMeanSpectrumAt (unsigned short band)
std::vector< float > getMeanSpectrum ()
unsigned short getLowestCostClass ()
double cutCost (bool useStdCut)
histogramModel * clone ()
void releaseHistogram ()
unsigned short getNClasses ()
void printHistogram ()
std::vector< double > getProbability ()
Public Member Functions inherited from regionModel
virtual ~regionModel ()
virtual void setNode (Node *n)
Node * getNode ()
void setArea (unsigned long a)
unsigned long getArea ()
Protected Attributes
std::vector< std::vector< float > > histograms
std::vector< float > meanSpectrum
std::vector< float > std
unsigned short nbands
unsigned short nbins
Protected Attributes inherited from regionModel
Node * node
unsigned long area
Additional Inherited Members
Public Attributes inherited from regionModel
bool useStdCut
Detailed Description
Definition at line 30 of file histogrammodel.h.
Constructor & Destructor Documentation
histogramModel() [1/2]
histogramModel::histogramModel (unsigned short bands, unsigned short bins)
Definition at line 27 of file histogrammodel.cpp.
References nbands, nbins, and regionModel::setArea().
Referenced by clone(), and merge().
histogramModel() [2/2]
histogramModel::histogramModel (const std::vector< float > & spectrum, unsigned nBins, const std::vector< double > & min, const std::vector< double > & max)
Definition at line 35 of file histogrammodel.cpp.
References histograms, increaseHistogramValue(), meanSpectrum, nbands, nbins, and regionModel::setArea().
~histogramModel()
virtual histogramModel::~histogramModel () inline virtual
Definition at line 36 of file histogrammodel.h.
Member Function Documentation
clone()
histogramModel * histogramModel::clone () virtual
Implements regionModel.
Definition at line 254 of file histogrammodel.cpp.
References regionModel::area, histogramModel(), nbands, nbins, and regionModel::setArea().
Referenced by compoundModel::clone().
cutCost()
double histogramModel::cutCost (bool useStdCut) virtual
Implements regionModel.
Definition at line 237 of file histogrammodel.cpp.
References regionModel::area, and nbands.
Referenced by compoundModel::cutCost().
getBand()
const std::vector< float > & histogramModel::getBand (unsigned short b)
Definition at line 182 of file histogrammodel.cpp.
References histograms.
Referenced by getOrder().
getLowestCostClass()
unsigned short histogramModel::getLowestCostClass () inline virtual
Implements regionModel.
Definition at line 69 of file histogrammodel.h.
getMeanSpectrum()
std::vector< float > histogramModel::getMeanSpectrum () virtual
Implements regionModel.
Definition at line 297 of file histogrammodel.cpp.
References meanSpectrum.
Referenced by compoundModel::getMeanSpectrum().
getMeanSpectrumAt()
float histogramModel::getMeanSpectrumAt (unsigned short band) virtual
Implements regionModel.
Definition at line 230 of file histogrammodel.cpp.
References meanSpectrum.
Referenced by compoundModel::getMeanSpectrumAt(), and merge().
getModel()
histogramModel * histogramModel::getModel () virtual
Implements regionModel.
Definition at line 86 of file histogrammodel.cpp.
getNBands()
unsigned short histogramModel::getNBands ()
Definition at line 187 of file histogrammodel.cpp.
References nbands.
getNBins()
unsigned short histogramModel::getNBins ()
Definition at line 192 of file histogrammodel.cpp.
References nbins.
getNClasses()
unsigned short histogramModel::getNClasses ()
Definition at line 275 of file histogrammodel.cpp.
getOrder()
double histogramModel::getOrder (regionModel * other) virtual
Implements regionModel.
Definition at line 59 of file histogrammodel.cpp.
References statistics::EMD(), getBand(), histograms, and nbands.
Referenced by compoundModel::getOrder().
getProbability()
std::vector<double> histogramModel::getProbability () inline virtual
Implements regionModel.
Definition at line 83 of file histogrammodel.h.
getSpectrum()
std::vector< float > & histogramModel::getSpectrum ()
Definition at line 210 of file histogrammodel.cpp.
References meanSpectrum.
getStd()
std::vector< float > & histogramModel::getStd ()
Definition at line 215 of file histogrammodel.cpp.
References std.
Referenced by merge().
getValue()
float histogramModel::getValue (unsigned short band, unsigned short bin)
Definition at line 174 of file histogrammodel.cpp.
References histograms.
Referenced by merge().
increaseHistogramValue()
void histogramModel::increaseHistogramValue (unsigned short band, unsigned short bin)
Definition at line 164 of file histogrammodel.cpp.
References histograms.
Referenced by histogramModel().
increaseHistogramValueBy()
void histogramModel::increaseHistogramValueBy (unsigned short band, unsigned short bin, float v)
Definition at line 169 of file histogrammodel.cpp.
References histograms.
merge()
histogramModel * histogramModel::merge (regionModel * other) virtual
Implements regionModel.
Definition at line 91 of file histogrammodel.cpp.
References regionModel::getArea(), getMeanSpectrumAt(), getStd(), getValue(), histogramModel(), histograms, meanSpectrum, nbands, nbins, releaseHistogram(), regionModel::setArea(), setHistogramValue(), setMeanSpectrumAt(), and setStd().
Referenced by compoundModel::merge().
normalizeBand()
void histogramModel::normalizeBand (unsigned short band)
Definition at line 197 of file histogrammodel.cpp.
References histograms, and nbins.
printHistogram()
void histogramModel::printHistogram () virtual
Implements regionModel.
Definition at line 281 of file histogrammodel.cpp.
References histograms.
Referenced by compoundModel::printHistogram().
releaseHistogram()
void histogramModel::releaseHistogram ()
Definition at line 266 of file histogrammodel.cpp.
References histograms.
Referenced by merge().
setHistogramValue()
void histogramModel::setHistogramValue (unsigned short band, unsigned short bin, float p)
Definition at line 159 of file histogrammodel.cpp.
References histograms.
Referenced by merge().
setMeanSpectrumAt()
void histogramModel::setMeanSpectrumAt (unsigned short band, float value)
Definition at line 221 of file histogrammodel.cpp.
References meanSpectrum.
Referenced by merge().
setStd()
void histogramModel::setStd (unsigned short band, float value)
Definition at line 226 of file histogrammodel.cpp.
Referenced by merge().
Member Data Documentation
histograms
std::vector< std::vector<float> > histogramModel::histograms protected
Definition at line 88 of file histogrammodel.h.
Referenced by getBand(), getOrder(), getValue(), histogramModel(), increaseHistogramValue(), increaseHistogramValueBy(), merge(), normalizeBand(), printHistogram(), releaseHistogram(), and setHistogramValue().
meanSpectrum
std::vector<float> histogramModel::meanSpectrum protected
Definition at line 89 of file histogrammodel.h.
Referenced by getMeanSpectrum(), getMeanSpectrumAt(), getSpectrum(), histogramModel(), merge(), and setMeanSpectrumAt().
nbands
unsigned short histogramModel::nbands protected
Definition at line 93 of file histogrammodel.h.
Referenced by clone(), cutCost(), getNBands(), getOrder(), histogramModel(), and merge().
nbins
unsigned short histogramModel::nbins protected
Definition at line 94 of file histogrammodel.h.
Referenced by clone(), getNBins(), histogramModel(), merge(), and normalizeBand().
std
std::vector<float> histogramModel::std protected
Definition at line 90 of file histogrammodel.h.
Referenced by getStd().
The documentation for this class was generated from the following files:
histogrammodel.h
histogrammodel.cpp