LSBPT: Node Class Reference
Node Class Reference
#include <node.h>
Public Member Functions
Node ()
~Node ()
void addEdge (Edge *e)
void removeEdge (Edge *e)
void removeAllEdges ()
std::vector< Edge * > & getEdges ()
void setParent (Node *n)
void setLeftChild (Node *n)
void setRightChild (Node *n)
Node * getParent ()
Node * getLeftChild ()
Node * getRightChild ()
Node * getSibling ()
void replaceChild (Node *old, Node *new_)
bool isLeaf ()
bool isChildOf (Node *n)
void setModel (regionModel *m)
regionModel * getModel ()
void replaceModel (regionModel *m)
void setPosition (Point p)
Point getPosition ()
long int getArea ()
float getMeanSpectrumAt (unsigned short ind)
std::vector< float > getMeanSpectrum ()
std::vector< double > getProbability ()
int getClassLabel ()
void releaseNode ()
void releaseTree ()
std::vector< int > getBoarderIndexX ()
std::vector< int > getBoarderIndexY ()
void setBoarderIndexX (int x)
void setBoarderIndexX (std::vector< int > index)
void setBoarderIndexY (int y)
void setBoarderIndexY (std::vector< int > index)
Static Public Member Functions
static bool nodeComparator_X (Node *e1, Node *e2)
static bool nodeComparator_Y (Node *e1, Node *e2)
Public Attributes
bool ifLeaf
int minPosition
int maxPosition
Private Attributes
Node * parent
Node * leftChild
Node * rightChild
std::vector< Edge * > edges
regionModel * model
Point position
std::vector< std::vector< int > > boarderIndex
std::vector< int > boarderIndexX
std::vector< int > boarderIndexY
Detailed Description
Definition at line 51 of file node.h.
Constructor & Destructor Documentation
Node()
Node::Node ()
Definition at line 23 of file node.cpp.
References ifLeaf, leftChild, maxPosition, minPosition, model, parent, and rightChild.
~Node()
Node::~Node ()
Definition at line 35 of file node.cpp.
Member Function Documentation
addEdge()
void Node::addEdge (Edge * e)
Definition at line 41 of file node.cpp.
References edges.
Referenced by initializer::addEdges(), initializer::connect(), and RAG::merge().
getArea()
long int Node::getArea ()
Definition at line 182 of file node.cpp.
References regionModel::getArea(), and model.
Referenced by EdgeHeap::edgeComparator().
getBoarderIndexX()
std::vector< int > Node::getBoarderIndexX ()
Definition at line 283 of file node.cpp.
References boarderIndexX.
Referenced by RAG::merge(), and io::writeBoarderNodeToCSV().
getBoarderIndexY()
std::vector< int > Node::getBoarderIndexY ()
Definition at line 287 of file node.cpp.
References boarderIndexY.
Referenced by RAG::merge(), and io::writeBoarderNodeToCSV().
getClassLabel()
int Node::getClassLabel ()
Definition at line 203 of file node.cpp.
References regionModel::getProbability(), and model.
getEdges()
std::vector< Edge * > & Node::getEdges ()
Definition at line 68 of file node.cpp.
References edges.
Referenced by RAG::merge().
getLeftChild()
Node * Node::getLeftChild ()
Definition at line 106 of file node.cpp.
References leftChild.
Referenced by io::bestSegmentation(), getSibling(), releaseTree(), io::writeBoarderNodeToCSV(), io::writeClassMap(), io::writeNodeToCSV(), and io::writeNodeToDisk().
getMeanSpectrum()
std::vector< float > Node::getMeanSpectrum ()
Definition at line 193 of file node.cpp.
References regionModel::getMeanSpectrum(), and model.
Referenced by io::writeBoarderNodeToCSV().
getMeanSpectrumAt()
float Node::getMeanSpectrumAt (unsigned short ind)
Definition at line 189 of file node.cpp.
References regionModel::getMeanSpectrumAt(), and model.
getModel()
regionModel * Node::getModel ()
Definition at line 164 of file node.cpp.
References model.
Referenced by initializer::addEdges(), io::bestSegmentation(), initializer::connect(), RAG::merge(), releaseNode(), and releaseTree().
getParent()
Node * Node::getParent ()
Definition at line 101 of file node.cpp.
References parent.
Referenced by getSibling(), and isChildOf().
getPosition()
Point Node::getPosition ()
Definition at line 79 of file node.cpp.
References position.
Referenced by initializer::addEdges(), EdgeHeap::edgeComparator(), nodeComparator_X(), nodeComparator_Y(), io::writeBoarderNodeToCSV(), io::writeClassMap(), io::writeNodeToCSV(), and io::writeNodeToDisk().
getProbability()
std::vector< double > Node::getProbability ()
Definition at line 198 of file node.cpp.
References regionModel::getProbability(), and model.
Referenced by io::writeBoarderNodeToCSV().
getRightChild()
Node * Node::getRightChild ()
Definition at line 111 of file node.cpp.
References rightChild.
Referenced by io::bestSegmentation(), getSibling(), releaseTree(), io::writeBoarderNodeToCSV(), io::writeClassMap(), io::writeNodeToCSV(), and io::writeNodeToDisk().
getSibling()
Node * Node::getSibling ()
Definition at line 116 of file node.cpp.
References getLeftChild(), getParent(), getRightChild(), and parent.
isChildOf()
bool Node::isChildOf (Node * n)
Definition at line 143 of file node.cpp.
References getParent().
isLeaf()
bool Node::isLeaf ()
Definition at line 135 of file node.cpp.
References ifLeaf.
Referenced by io::bestSegmentation(), releaseTree(), io::writeBoarderNodeToCSV(), io::writeClassMap(), io::writeNodeToCSV(), and io::writeNodeToDisk().
nodeComparator_X()
bool Node::nodeComparator_X (Node * e1, Node * e2) static
Definition at line 256 of file node.cpp.
References getPosition().
Referenced by initializer::addEdges().
nodeComparator_Y()
bool Node::nodeComparator_Y (Node * e1, Node * e2) static
Definition at line 267 of file node.cpp.
References getPosition().
Referenced by initializer::addEdges().
releaseNode()
void Node::releaseNode ()
Definition at line 211 of file node.cpp.
References edges, and getModel().
releaseTree()
void Node::releaseTree ()
Delete all nodes and edges. This method delete the tree recursively. All edges, node, and Models are deleted.
Definition at line 224 of file node.cpp.
References edges, getLeftChild(), getModel(), getRightChild(), isLeaf(), and releaseTree().
Referenced by image::mergeBlockX(), image::mergeBlockY(), imageblock::processing(), and releaseTree().
removeAllEdges()
void Node::removeAllEdges ()
Definition at line 62 of file node.cpp.
References edges.
Referenced by RAG::merge().
removeEdge()
void Node::removeEdge (Edge * e)
Definition at line 46 of file node.cpp.
References edges.
Referenced by RAG::merge(), and RAG::regionMerging().
replaceChild()
void Node::replaceChild (Node * old, Node * new_)
Definition at line 127 of file node.cpp.
References leftChild, and rightChild.
replaceModel()
void Node::replaceModel (regionModel * m)
Definition at line 169 of file node.cpp.
References model, and setModel().
setBoarderIndexX() [1/2]
void Node::setBoarderIndexX (int x)
Definition at line 291 of file node.cpp.
References boarderIndexX.
Referenced by initializer::createNodeMatrix(), RAG::merge(), and image::selectBoarderSegments().
setBoarderIndexX() [2/2]
void Node::setBoarderIndexX (std::vector< int > index)
Definition at line 302 of file node.cpp.
References boarderIndexX.
setBoarderIndexY() [1/2]
void Node::setBoarderIndexY (int y)
Definition at line 296 of file node.cpp.
References boarderIndexY.
Referenced by initializer::createNodeMatrix(), RAG::merge(), and image::selectBoarderSegments().
setBoarderIndexY() [2/2]
void Node::setBoarderIndexY (std::vector< int > index)
Definition at line 307 of file node.cpp.
References boarderIndexY.
setLeftChild()
void Node::setLeftChild (Node * n)
Definition at line 91 of file node.cpp.
References leftChild.
Referenced by RAG::merge().
setModel()
void Node::setModel (regionModel * m)
Definition at line 158 of file node.cpp.
References model, and regionModel::setNode().
Referenced by RAG::merge(), replaceModel(), and image::selectBoarderSegments().
setParent()
void Node::setParent (Node * n)
Definition at line 86 of file node.cpp.
References parent.
Referenced by RAG::merge().
setPosition()
void Node::setPosition (Point p)
Definition at line 74 of file node.cpp.
References position.
Referenced by initializer::createNodeMatrix(), and image::selectBoarderSegments().
setRightChild()
void Node::setRightChild (Node * n)
Definition at line 96 of file node.cpp.
References rightChild.
Referenced by RAG::merge().
Member Data Documentation
boarderIndex
std::vector<std::vector<int> > Node::boarderIndex private
Definition at line 134 of file node.h.
boarderIndexX
std::vector<int> Node::boarderIndexX private
Definition at line 136 of file node.h.
Referenced by getBoarderIndexX(), and setBoarderIndexX().
boarderIndexY
std::vector<int> Node::boarderIndexY private
Definition at line 137 of file node.h.
Referenced by getBoarderIndexY(), and setBoarderIndexY().
edges
std::vector<Edge*> Node::edges private
Definition at line 127 of file node.h.
Referenced by addEdge(), getEdges(), releaseNode(), releaseTree(), removeAllEdges(), and removeEdge().
ifLeaf
bool Node::ifLeaf
Definition at line 119 of file node.h.
Referenced by initializer::createNodeMatrix(), isLeaf(), Node(), and image::selectBoarderSegments().
leftChild
Node* Node::leftChild private
Definition at line 124 of file node.h.
Referenced by getLeftChild(), Node(), replaceChild(), and setLeftChild().
maxPosition
int Node::maxPosition
Definition at line 121 of file node.h.
Referenced by Node().
minPosition
int Node::minPosition
Definition at line 120 of file node.h.
Referenced by Node().
model
regionModel* Node::model private
Definition at line 129 of file node.h.
Referenced by getArea(), getClassLabel(), getMeanSpectrum(), getMeanSpectrumAt(), getModel(), getProbability(), Node(), replaceModel(), and setModel().
parent
Node* Node::parent private
Definition at line 123 of file node.h.
Referenced by getParent(), getSibling(), Node(), and setParent().
position
Point Node::position private
Definition at line 131 of file node.h.
Referenced by getPosition(), and setPosition().
rightChild
Node* Node::rightChild private
Definition at line 125 of file node.h.
Referenced by getRightChild(), Node(), replaceChild(), and setRightChild().
The documentation for this class was generated from the following files:
node.h
node.cpp