LSBPT: statistics Class Reference
statistics Class Reference
#include <statistics.h>
Classes
class distribution
Public Member Functions
statistics ()
Static Public Member Functions
static float bhatt (const std::vector< float > &X, const std::vector< float > &Y)
static float bhatt (float X[], float Y[], unsigned short n)
static float EMD (const std::vector< float > &X, const std::vector< float > &Y)
static float abs (float v)
static float correlation (const std::vector< float > &X, const std::vector< float > &Y)
Detailed Description
Definition at line 39 of file statistics.h.
Constructor & Destructor Documentation
statistics()
statistics::statistics ()
Definition at line 23 of file statistics.cpp.
Member Function Documentation
abs()
float statistics::abs (float v) static
Definition at line 104 of file statistics.cpp.
Referenced by EMD().
bhatt() [1/2]
float statistics::bhatt (const std::vector< float > & X, const std::vector< float > & Y) static
Definition at line 29 of file statistics.cpp.
bhatt() [2/2]
float statistics::bhatt (float X[], float Y[], unsigned short n) static
Definition at line 47 of file statistics.cpp.
correlation()
float statistics::correlation (const std::vector< float > & X, const std::vector< float > & Y) static
Definition at line 113 of file statistics.cpp.
EMD()
float statistics::EMD (const std::vector< float > & X, const std::vector< float > & Y) static
Definition at line 68 of file statistics.cpp.
References abs().
Referenced by histogramModel::getOrder().
The documentation for this class was generated from the following files:
statistics.h
statistics.cpp