LSBPT: RAG Class Reference
RAG Class Reference
#include <rag.h>
Public Member Functions
RAG ()
~RAG ()
void addNode (Node *n)
void addEdge (Edge *e)
int getNodeSize ()
int getEdgeSize ()
Node * regionMerging ()
Node * merge (Node *n1, Node *n2)
Public Attributes
int width
int height
std::vector< pair< Node *, Node * > > pixelPairs
std::vector< std::vector< Node * > > nodeMatrix
QSet< Node * > nodes
Private Attributes
EdgeHeap edges
Detailed Description
Definition at line 43 of file rag.h.
Constructor & Destructor Documentation
RAG()
RAG::RAG ()
Definition at line 24 of file rag.cpp.
~RAG()
RAG::~RAG ()
Definition at line 27 of file rag.cpp.
Member Function Documentation
addEdge()
void RAG::addEdge (Edge * e)
Definition at line 49 of file rag.cpp.
References edges, and EdgeHeap::push_back().
Referenced by initializer::addEdges(), and initializer::connect().
addNode()
void RAG::addNode (Node * n)
Definition at line 32 of file rag.cpp.
References nodes.
Referenced by initializer::addNodesToRAG(), and initializer::initializeRag().
getEdgeSize()
int RAG::getEdgeSize ()
Definition at line 43 of file rag.cpp.
References edges, and EdgeHeap::size().
getNodeSize()
int RAG::getNodeSize ()
Definition at line 39 of file rag.cpp.
References nodes.
merge()
Node * RAG::merge (Node * n1, Node * n2)
Merge to Nodes.
Parameters
n1 First node.
n2 Second node.
Returns
A Node object, which the the parent node of n1 and n2.
This method merges two node into a parent node. It tracks the borders, merges the regionModel update edges, and sort the heap after each update.
efficient perimeter computation:
Definition at line 117 of file rag.cpp.
References Node::addEdge(), edges, Node::getBoarderIndexX(), Node::getBoarderIndexY(), Node::getEdges(), Edge::getLength(), Node::getModel(), Edge::getNode1(), Edge::getNode2(), regionModel::merge(), nodes, EdgeHeap::remove(), Node::removeAllEdges(), Node::removeEdge(), Node::setBoarderIndexX(), Node::setBoarderIndexY(), Node::setLeftChild(), Edge::setLength(), Node::setModel(), Node::setParent(), Node::setRightChild(), and EdgeHeap::update().
Referenced by regionMerging().
regionMerging()
Node * RAG::regionMerging ()
Create a BPT
Returns
A Node, which is the root of the tree. This method takes a initialized rag, merges two regions each time till one Node left.
Definition at line 65 of file rag.cpp.
References edges, EdgeHeap::getFront(), Edge::getNode1(), Edge::getNode2(), EdgeHeap::heapify(), merge(), nodes, Node::removeEdge(), EdgeHeap::removeFront(), and EdgeHeap::size().
Referenced by imageblock::createBPT(), image::mergeBlockX(), and image::mergeBlockY().
Member Data Documentation
edges
EdgeHeap RAG::edges private
Definition at line 68 of file rag.h.
Referenced by addEdge(), getEdgeSize(), merge(), and regionMerging().
height
int RAG::height
Definition at line 57 of file rag.h.
Referenced by initializer::multispectralImageToRAG(), and initializer::multispectralImageToRAG2().
nodeMatrix
std::vector< std::vector<Node*> > RAG::nodeMatrix
Definition at line 59 of file rag.h.
Referenced by initializer::multispectralImageToRAG(), and initializer::multispectralImageToRAG2().
nodes
QSet<Node*> RAG::nodes
Definition at line 60 of file rag.h.
Referenced by addNode(), getNodeSize(), merge(), and regionMerging().
pixelPairs
std::vector< pair<Node*,Node*> > RAG::pixelPairs
Definition at line 58 of file rag.h.
Referenced by initializer::connect().
width
int RAG::width
Definition at line 57 of file rag.h.
Referenced by initializer::multispectralImageToRAG(), and initializer::multispectralImageToRAG2().
The documentation for this class was generated from the following files:
rag.h
rag.cpp