LSBPT: probabilityModel Class Reference
probabilityModel Class Reference
#include <probabilitymodel.h>
Public Member Functions
probabilityModel ()
probabilityModel (const std::vector< double > &probabilities)
virtual ~probabilityModel ()
probabilityModel * merge (regionModel *other)
double getOrder (regionModel *other)
probabilityModel * clone ()
double computeRegionClassCost (unsigned short class_)
double computeRegionCost ()
unsigned short getNClasses ()
std::vector< double > & getClassProbabilities ()
void setClassProbability (unsigned short class_, double value)
void setClassProbabilities (std::vector< double > value)
double getClassProbability (unsigned short class_)
std::vector< double > getClassCosts () const
void setClassCosts (std::vector< double > value)
void setClassCostsWithProbability (std::vector< double > probability)
void setClassCost (unsigned short class_, double value)
double getClassCost (unsigned short class_)
double getLowestCost ()
unsigned short getLowestCostClass ()
probabilityModel * getModel ()
std::vector< double > getProbability ()
double cutCost (bool useStdCut)
return the probability std::vector
float getMeanSpectrumAt (unsigned short band)
std::vector< float > getMeanSpectrum ()
void printHistogram ()
Public Member Functions inherited from regionModel
virtual ~regionModel ()
virtual void setNode (Node *n)
Node * getNode ()
void setArea (unsigned long a)
unsigned long getArea ()
Private Attributes
std::vector< double > classProbabilities
std::vector< double > classCosts
Additional Inherited Members
Public Attributes inherited from regionModel
bool useStdCut
Protected Attributes inherited from regionModel
Node * node
unsigned long area
Detailed Description
Definition at line 25 of file probabilitymodel.h.
Constructor & Destructor Documentation
probabilityModel() [1/2]
probabilityModel::probabilityModel ()
Definition at line 16 of file probabilitymodel.cpp.
References regionModel::setArea().
Referenced by clone(), and merge().
probabilityModel() [2/2]
probabilityModel::probabilityModel (const std::vector< double > & probabilities)
Definition at line 22 of file probabilitymodel.cpp.
References classProbabilities, regionModel::setArea(), and setClassCost().
~probabilityModel()
probabilityModel::~probabilityModel () virtual
Definition at line 37 of file probabilitymodel.cpp.
Member Function Documentation
clone()
probabilityModel * probabilityModel::clone () virtual
Implements regionModel.
Definition at line 115 of file probabilitymodel.cpp.
References regionModel::area, classCosts, classProbabilities, probabilityModel(), regionModel::setArea(), setClassCosts(), and setClassProbabilities().
computeRegionClassCost()
double probabilityModel::computeRegionClassCost (unsigned short class_)
Definition at line 131 of file probabilitymodel.cpp.
References getClassCost().
computeRegionCost()
double probabilityModel::computeRegionCost ()
Definition at line 139 of file probabilitymodel.cpp.
cutCost()
double probabilityModel::cutCost (bool useStdCut) virtual
return the probability std::vector
Implements regionModel.
Definition at line 238 of file probabilitymodel.cpp.
References classCosts.
Referenced by compoundModel::cutCost().
getClassCost()
double probabilityModel::getClassCost (unsigned short class_)
Definition at line 232 of file probabilitymodel.cpp.
References classCosts.
Referenced by computeRegionClassCost(), and merge().
getClassCosts()
std::vector< double > probabilityModel::getClassCosts () const
Definition at line 204 of file probabilitymodel.cpp.
References classCosts.
getClassProbabilities()
std::vector< double > & probabilityModel::getClassProbabilities ()
Definition at line 154 of file probabilitymodel.cpp.
References classProbabilities.
getClassProbability()
double probabilityModel::getClassProbability (unsigned short class_)
Definition at line 172 of file probabilitymodel.cpp.
References classProbabilities.
Referenced by getOrder(), and merge().
getLowestCost()
double probabilityModel::getLowestCost ()
Definition at line 177 of file probabilitymodel.cpp.
References classCosts.
getLowestCostClass()
unsigned short probabilityModel::getLowestCostClass () virtual
Implements regionModel.
Definition at line 189 of file probabilitymodel.cpp.
References classCosts.
Referenced by compoundModel::getLowestCostClass().
getMeanSpectrum()
std::vector<float> probabilityModel::getMeanSpectrum () inline virtual
Implements regionModel.
Definition at line 77 of file probabilitymodel.h.
getMeanSpectrumAt()
float probabilityModel::getMeanSpectrumAt (unsigned short band) inline virtual
Implements regionModel.
Definition at line 76 of file probabilitymodel.h.
getModel()
probabilityModel * probabilityModel::getModel () virtual
Implements regionModel.
Definition at line 90 of file probabilitymodel.cpp.
getNClasses()
unsigned short probabilityModel::getNClasses ()
Definition at line 149 of file probabilitymodel.cpp.
References classProbabilities.
Referenced by merge().
getOrder()
double probabilityModel::getOrder (regionModel * other) virtual
Implements regionModel.
Definition at line 95 of file probabilitymodel.cpp.
References classProbabilities, and getClassProbability().
Referenced by compoundModel::getOrder().
getProbability()
std::vector< double > probabilityModel::getProbability () virtual
Implements regionModel.
Definition at line 76 of file probabilitymodel.cpp.
References classProbabilities.
Referenced by compoundModel::getProbability().
merge()
probabilityModel * probabilityModel::merge (regionModel * other) virtual
Implements regionModel.
Definition at line 42 of file probabilitymodel.cpp.
References classCosts, classProbabilities, regionModel::getArea(), getClassCost(), getClassProbability(), getNClasses(), probabilityModel(), regionModel::setArea(), setClassCost(), and setClassProbability().
Referenced by compoundModel::merge().
printHistogram()
void probabilityModel::printHistogram () inline virtual
Implements regionModel.
Definition at line 79 of file probabilitymodel.h.
setClassCost()
void probabilityModel::setClassCost (unsigned short class_, double value)
Definition at line 223 of file probabilitymodel.cpp.
References classCosts.
Referenced by initializer::addProbModel(), merge(), probabilityModel(), and setClassCostsWithProbability().
setClassCosts()
void probabilityModel::setClassCosts (std::vector< double > value)
Definition at line 210 of file probabilitymodel.cpp.
References classCosts.
Referenced by clone().
setClassCostsWithProbability()
void probabilityModel::setClassCostsWithProbability (std::vector< double > probability)
Definition at line 215 of file probabilitymodel.cpp.
References setClassCost().
setClassProbabilities()
void probabilityModel::setClassProbabilities (std::vector< double > value)
Definition at line 167 of file probabilitymodel.cpp.
References classProbabilities.
Referenced by clone().
setClassProbability()
void probabilityModel::setClassProbability (unsigned short class_, double value)
Definition at line 159 of file probabilitymodel.cpp.
References classProbabilities.
Referenced by initializer::addProbModel(), and merge().
Member Data Documentation
classCosts
std::vector<double> probabilityModel::classCosts private
Definition at line 99 of file probabilitymodel.h.
Referenced by clone(), cutCost(), getClassCost(), getClassCosts(), getLowestCost(), getLowestCostClass(), merge(), setClassCost(), and setClassCosts().
classProbabilities
std::vector<double> probabilityModel::classProbabilities private
Definition at line 97 of file probabilitymodel.h.
Referenced by clone(), getClassProbabilities(), getClassProbability(), getNClasses(), getOrder(), getProbability(), merge(), probabilityModel(), setClassProbabilities(), and setClassProbability().
The documentation for this class was generated from the following files:
probabilitymodel.h
probabilitymodel.cpp