LSBPT: initializer Class Reference
initializer Class Reference
#include <initializer.h>
Static Public Member Functions
static void initializeRag (RAG &rag, std::vector< Node *> &selectedNodeSet)
static std::vector< std::vector< Node * > > createNodeMatrix (int blockStartX, int blockStartY, int blockSizeW, int blockSizeH, int globalStartX, int globalStartY, int globalSizeW, int globalSizeH)
static void addEdges (std::vector< Node *> NodeSet, RAG &out)
template<typename T >
static RAG multispectralImageToRAG2 (std::vector< Mat > images, std::vector< int > blockPosition, std::vector< std::vector< std::vector< double > > > &probabilites)
template<typename T >
static RAG multispectralImageToRAG (std::vector< Mat > images, std::vector< std::vector< std::vector< double > > > &probabilites, int blockStartX, int blockStartY, int blockSizeX, int blockSizeY, int globalStaetX, int globalStartY, int globalsizeX, int globalSizeY, std::vector< double > orderMin, std::vector< double > orderMax, int nBins)
Static Private Member Functions
static void connect (RAG &out, std::vector< std::vector< Node *> > &nodeMatrix)
static std::vector< std::vector< Node * > > createNodeMatrix2 (int height, int width, std::vector< int > blockPosition)
static void addNodesToRAG (const std::vector< std::vector< Node *> > &nodeMatrix, RAG &rag)
static void addProbModel (std::vector< std::vector< Node *> > &nodeMatrix, std::vector< std::vector< std::vector< double > > > &probabilites)
static void addEmpytHistModel (std::vector< std::vector< Node *> > &nodeMatrix, unsigned short nbands, int nBins)
template<typename T >
static void addHistModel (std::vector< std::vector< Node *> > &nodeMatrix, std::vector< Mat > images, int nBins)
template<typename T >
static void addHistModel (std::vector< std::vector< Node *> > &nodeMatrix, std::vector< Mat > images, std::vector< double > orderMin, std::vector< double > orderMax, int nBins)
template<typename T >
static void addHistogramOneBand (int band, double min, double max, int nbins, Mat image, std::vector< std::vector< Node *> > &nodeMatrix)
template<typename T >
static void addMeanSpectrumInformation (unsigned short band, Mat image, std::vector< std::vector< Node *> > &nodeMatrix)
Detailed Description
Definition at line 36 of file initializer.h.
Member Function Documentation
addEdges()
static void initializer::addEdges (std::vector< Node *> NodeSet, RAG & out) inline static
Definition at line 46 of file initializer.h.
References RAG::addEdge(), Node::addEdge(), Node::getModel(), regionModel::getOrder(), Node::getPosition(), Node::nodeComparator_X(), Node::nodeComparator_Y(), Edge::setLength(), and Edge::setWeight().
Referenced by initializeRag().
addEmpytHistModel()
void initializer::addEmpytHistModel (std::vector< std::vector< Node *> > & nodeMatrix, unsigned short nbands, int nBins) static private
Definition at line 97 of file initializer.cpp.
References compoundModel::setHistogramModel().
addHistModel() [1/2]
template<typename T > static void initializer::addHistModel (std::vector< std::vector< Node *> > & nodeMatrix, std::vector< Mat > images, int nBins) inline static private
Definition at line 224 of file initializer.h.
addHistModel() [2/2]
template<typename T > static void initializer::addHistModel (std::vector< std::vector< Node *> > & nodeMatrix, std::vector< Mat > images, std::vector< double > orderMin, std::vector< double > orderMax, int nBins) inline static private
Definition at line 245 of file initializer.h.
addHistogramOneBand()
template<typename T > static void initializer::addHistogramOneBand (int band, double min, double max, int nbins, Mat image, std::vector< std::vector< Node *> > & nodeMatrix) inline static private
Definition at line 261 of file initializer.h.
addMeanSpectrumInformation()
template<typename T > static void initializer::addMeanSpectrumInformation (unsigned short band, Mat image, std::vector< std::vector< Node *> > & nodeMatrix) inline static private
Definition at line 277 of file initializer.h.
addNodesToRAG()
void initializer::addNodesToRAG (const std::vector< std::vector< Node *> > & nodeMatrix, RAG & rag) static private
Definition at line 119 of file initializer.cpp.
References RAG::addNode().
addProbModel()
void initializer::addProbModel (std::vector< std::vector< Node *> > & nodeMatrix, std::vector< std::vector< std::vector< double > > > & probabilites) static private
Definition at line 198 of file initializer.cpp.
References probabilityModel::setClassCost(), and probabilityModel::setClassProbability().
connect()
void initializer::connect (RAG & out, std::vector< std::vector< Node *> > & nodeMatrix) static private
Definition at line 132 of file initializer.cpp.
References RAG::addEdge(), Node::addEdge(), Node::getModel(), regionModel::getOrder(), RAG::pixelPairs, Edge::setLength(), and Edge::setWeight().
createNodeMatrix()
std::vector< std::vector< Node * > > initializer::createNodeMatrix (int blockStartX, int blockStartY, int blockSizeW, int blockSizeH, int globalStartX, int globalStartY, int globalSizeW, int globalSizeH) static
Definition at line 27 of file initializer.cpp.
References Node::ifLeaf, Node::setBoarderIndexX(), Node::setBoarderIndexY(), and Node::setPosition().
createNodeMatrix2()
static std::vector< std::vector<Node*> > initializer::createNodeMatrix2 (int height, int width, std::vector< int > blockPosition) static private
initializeRag()
void initializer::initializeRag (RAG & rag, std::vector< Node *> & selectedNodeSet) static
Definition at line 235 of file initializer.cpp.
References addEdges(), and RAG::addNode().
Referenced by image::mergeBlockX(), and image::mergeBlockY().
multispectralImageToRAG()
template<typename T > static RAG initializer::multispectralImageToRAG (std::vector< Mat > images, std::vector< std::vector< std::vector< double > > > & probabilites, int blockStartX, int blockStartY, int blockSizeX, int blockSizeY, int globalStaetX, int globalStartY, int globalsizeX, int globalSizeY, std::vector< double > orderMin, std::vector< double > orderMax, int nBins) inline static
Initialize a rag for a tile.
Parameters
images A vector of Mat which stores color information for each band
blockPosition A vector of lenght 2 which stores the index of t he tile which is going to be process, the first element represents the index in X direction (horizontal), and the other represents the index in Y direction (verticle).
probabilities A 3D vector, the first dimension represents the cordinate in Y direction, the second dimension represnts the cordinate in X direction, and the third dimension represnts the class probabilities of the pixel
Returns
A initialized rag, see RAG.
Definition at line 145 of file initializer.h.
References RAG::height, RAG::nodeMatrix, and RAG::width.
multispectralImageToRAG2()
template<typename T > static RAG initializer::multispectralImageToRAG2 (std::vector< Mat > images, std::vector< int > blockPosition, std::vector< std::vector< std::vector< double > > > & probabilites) inline static
Initialize a rag for a tile.
Parameters
images A vector of Mat which stores color information for each band
blockPosition A vector of lenght 2 which stores the index of t he tile which is going to be process, the first element represents the index in X direction (horizontal), and the other represents the index in Y direction (verticle).
probabilities A 3D vector, the first dimension represents the cordinate in Y direction, the second dimension represnts the cordinate in X direction, and the third dimension represnts the class probabilities of the pixel
Returns
A initialized rag, see RAG.
Definition at line 89 of file initializer.h.
References RAG::height, RAG::nodeMatrix, and RAG::width.
The documentation for this class was generated from the following files:
initializer.h
initializer.cpp